logging:
  file:
    name: logs/logs.txt
    path: logs
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false

server:
  port: 8080

security:
  user:
    name: ${SECURITY_USER_NAME}
    password: ${SECURITY_PASSWORD}