logging:
  file:
    name: logs/logs.txt
    path: logs
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: src/main/resources/ode-https.jks
    key-store-password: password
    key-password: password
    key-alias: ode-https
  http:
    port: 8080

  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-1
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.springframework.transaction.jta.JtaTransactionManager
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_PASSWORD}
  config:
    import: "optional:classpath:.env[.properties]"

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-time: 3600

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


app:
  first-user:
    name: ${FIRST_USER_NAME}
    password: ${FIRST_USER_PASSWORD}