logging:
  file:
    name: logs/logs.txt
    path: logs
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_PASSWORD}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600

app:
  first-user:
    name: ${FIRST_USER_NAME}
    password: ${FIRST_USER_PASSWORD}