spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

security:
  user:
    name: ${SECURITY_USER_NAME}
    password: ${SECURITY_PASSWORD}