name: Gradle Build

on:
  pull_request:
    branches:
      - master
      - develop

# Push checks are only performed when there is an open pull request the workflow will only run on pushes to branches
# that have an open pull request targeting the develop branch - include when readme.md is created
jobs:
  build:
    if: github.event_name == 'pull_request' || github.event_name == 'push' && github.event.pull_request != null
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Clean up
      run: rm -rf build